### ISSUE TITLE
Preview stops working after exceeding a certain amount of ellements

### ISSUE THREAD

**Issue by N247S** [SimonSiefke/vscode-html-preview#22]
I noticed that the preview (both in VSC and in the browser) are not able to load after a certain amount of elements (doesn't matter which type).

I added a text file containing html code which will cause the problem described above.

extension version: 1.21.0

[test.txt](https://github.com/SimonSiefke/vscode-html-preview/files/4402033/test.txt)

**Comment by SimonSiefke** [comment]
Thanks for the bug report. The too-many-elements issue should be fixed in version 1.21.5. 
There are still other bugs with `table` because the browser automatically inserts `<tbody>` inside `table`. A workaround would be writing 
```html
<table>
	<tbody>
		<tr><td>1</td></tr>
		<tr><td>2</td></tr>
	</tbody>
</table>
```
That way the code exactly matches the browser code and it should update without issues.

Let me know if you have any other issues!
